{{- if .Values.apiCustomers.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-customers-data
  labels:
    app: api-customers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apiCustomers.persistence.size }}
{{- end }}
