{{- if and .Values.apiKeys.enabled (or .Values.apiKeys.customers .Values.apiKeys.bills .Values.apiKeys.raiders) }}
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-api-keys
  labels:
    app.kubernetes.io/component: api-keys
type: Opaque
stringData:
  {{- if .Values.apiKeys.customers }}
  api-key-customers: {{ .Values.apiKeys.customers | quote }}
  {{- end }}
  {{- if .Values.apiKeys.bills }}
  api-key-bills: {{ .Values.apiKeys.bills | quote }}
  {{- end }}
  {{- if .Values.apiKeys.raiders }}
  api-key-raiders: {{ .Values.apiKeys.raiders | quote }}
  {{- end }}
{{- end }}
